### ISSUE TITLE
mnu unavailable via brew or website urls

### ISSUE THREAD

**Issue by walkertraylor** [smittytone/mnu#2]
Downloading via brew fails

❯ brew install mnu
==> Downloading https://smittytone.net/files/mnu/mnu_1_6_3h.dmg
curl: (22) The requested URL returned error: 404

Downloading via alternate url given on website also fails. (from https://smittytone.net/mnu/index.html)

❯ wget https://smittytone.net/files/mnu/mnu_1_6_3.dmg
--2023-01-16 08:56:21--  https://smittytone.net/files/mnu/mnu_1_6_3.dmg
Resolving smittytone.net (smittytone.net)... 35.214.88.128
Connecting to smittytone.net (smittytone.net)|35.214.88.128|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-01-16 08:56:22 ERROR 404: Not Found.

**Comment by smittytone** [comment]
So missed this comment. Should be fixed now for Homebrew. Website will be fixed later today.

Got bitten by macOS filename case insensitivity.
